### ISSUE TITLE
Hej jennie

### ISSUE THREAD

**Issue by Gustav-Pernber-nti-johanneberg** [jennie-edlund-nti-johanneberg/Mattespel_2#5]
Hej jennie

**Comment by jennie-edlund-nti-johanneberg** [comment]
vad

Den ons 19 jan. 2022 kl 03:22 skrev Gustav-Pernber-nti-johanneberg <
***@***.***>:

**Comment by Gustav-Pernber-nti-johanneberg** [comment]
Vgd?

**Comment by jennie-edlund-nti-johanneberg** [comment]
Not me!

Den ons 19 jan. 2022 kl 14:41 skrev Gustav-Pernber-nti-johanneberg <
***@***.***>:

**Comment by Gustav-Pernber-nti-johanneberg** [comment]
Hur![image](https://user-images.githubusercontent.com/74712621/150263804-09855318-d58b-4a84-824b-540ef39561bd.jpeg)

**Comment by jennie-edlund-nti-johanneberg** [comment]
Thanks!

Den tors 20 jan. 2022 kl 03:54 skrev Gustav-Pernber-nti-johanneberg <
***@***.***>:
